/*
 * Kamus Curso java Insafor 2022
 */
package intermedioT5;


import javax.swing.JOptionPane;

/*
 * @author Kamus
 */
public class panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDirec = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtSal = new javax.swing.JTextField();
        txtDesR = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(134, 91, 91));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        jLabel1.setText("Motursa Mantenimiento");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("N° Nit");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Dirección");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Teléfono");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Salario Mensual");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Descuento Renta");

        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRead.setText("Buscar");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48)
                        .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel5)
                        .addGap(48, 48, 48)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(44, 44, 44)
                                .addComponent(btnRead)
                                .addGap(37, 37, 37)
                                .addComponent(btnUpdate)
                                .addGap(44, 44, 44)
                                .addComponent(btnDelete)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDesR, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSal, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addComponent(btnClear)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtDesR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(20, 68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnRead)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnClear))))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        MotursaDAO md = new MotursaDAO();
        EHMotursa em = new EHMotursa();

        if (txtNit.getText().isEmpty() || txtName.getText().isEmpty()
                || txtDirec.getText().isEmpty() || txtTel.getText().isEmpty()
                || txtSal.getText().isEmpty() || txtDesR.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");

        } else if (md.consultar(txtNit.getText()) != null) {
            JOptionPane.showMessageDialog(null, "Nit ya registrado ");
        } else {

            em.setNoNit(txtNit.getText());
            em.setNombre(txtName.getText());
            em.setDireccion(txtDirec.getText());
            em.setTelefono(txtTel.getText());
            em.setSalarioMensual(Double.parseDouble(txtSal.getText()));
            em.setDecuentoRenta(Double.parseDouble(txtDesR.getText()));
            md.guardar(em);

            String data = "Usuario Creado con exito\n\n"
                    + "No Nit: " + txtNit.getText().toUpperCase() + "\n"
                    + "Nombre: " + txtName.getText().toUpperCase() + "\n"
                    + "Dirección: " + txtDirec.getText().toUpperCase() + "\n"
                    + "Teléfono: " + txtTel.getText().toUpperCase() + "\n"
                    + "Salario Mensual" + txtSal.getText().toUpperCase() + "\n"
                    + "Descuento Renta: " + txtDesR.getText().toUpperCase() + "\n";

            JOptionPane.showMessageDialog(null, data);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        txtNit.setText("");
        txtName.setText("");
        txtDirec.setText("");
        txtTel.setText("");
        txtSal.setText("");
        txtDesR.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        MotursaDAO md = new MotursaDAO();
        EHMotursa em = new EHMotursa();

        try {
            if (txtNit.getText().isEmpty() || txtName.getText().isEmpty()
                    || txtDirec.getText().isEmpty() || txtTel.getText().isEmpty()
                    || txtSal.getText().isEmpty() || txtDesR.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
            } else {

                em.setNombre(txtName.getText());
                em.setDireccion(txtDirec.getText());
                em.setTelefono(txtTel.getText());
                em.setSalarioMensual(Double.parseDouble(txtSal.getText()));
                em.setDecuentoRenta(Double.parseDouble(txtDesR.getText()));
                em.setNoNit(txtNit.getText());
                md.modificar(em);

                String data = "Usuario Actualizado\n\n"
                        + "No Nit: " + txtNit.getText().toUpperCase() + "\n"
                        + "Nombre: " + txtName.getText().toUpperCase() + "\n"
                        + "Dirección: " + txtDirec.getText().toUpperCase() + "\n"
                        + "Teléfono: " + txtTel.getText().toUpperCase() + "\n"
                        + "Salario Mensual" + txtSal.getText().toUpperCase() + "\n"
                        + "Descuento Renta: " + txtDesR.getText().toUpperCase() + "\n";

                JOptionPane.showMessageDialog(null, data);
            }

        } catch (NullPointerException ex) {
            ex.printStackTrace();
            System.out.println("erro testeo modal" + ex.getMessage());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        MotursaDAO md = new MotursaDAO();
        EHMotursa em = md.consultar(txtNit.getText());

        if (em == null) {
            txtNit.setText("Digite un Usuario");

            JOptionPane.showMessageDialog(null, "Usuario no existe ");
            txtNit.setText("");
        } else if (em != null) {
            txtNit.setText(em.getNoNit());
            txtName.setText(em.getNombre());
            txtDirec.setText(em.getDireccion());
            txtTel.setText(em.getTelefono());
            txtSal.setText(String.valueOf(em.getSalarioMensual()));
            txtDesR.setText(String.valueOf(em.getDecuentoRenta()));
            String data = "Datos del Usuario\n\n"
                    + "No Nit: " + txtNit.getText().toUpperCase() + "\n"
                    + "Nombre: " + txtName.getText().toUpperCase() + "\n"
                    + "Dirección: " + txtDirec.getText().toUpperCase() + "\n"
                    + "Teléfono: " + txtTel.getText().toUpperCase() + "\n"
                    + "Salario Mensual" + txtSal.getText().toUpperCase() + "\n"
                    + "Descuento Renta: " + txtDesR.getText().toUpperCase() + "\n";

            JOptionPane.showMessageDialog(null, data);

        }
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        MotursaDAO md = new MotursaDAO();
        EHMotursa em = md.consultar(txtNit.getText());

        if (txtNit.getText().isEmpty() || md.consultar(txtNit.getText()) == null) {
            txtNit.setText("Digite un Usuario");
        } else {

            txtName.setText(em.getNombre());
            txtDirec.setText(em.getDireccion());
            txtTel.setText(em.getTelefono());
            txtSal.setText(String.valueOf(em.getSalarioMensual()));
            txtDesR.setText(String.valueOf(em.getDecuentoRenta()));

            String opcion = JOptionPane.showInputDialog("¿Desea eliminar el usuario permanentemente? \n"
                    + "Si S / No N").toUpperCase();
            if (opcion.equals("S")) {
                JOptionPane.showMessageDialog(null, "Usuario eliminado");
                md.eliminar(txtNit.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Usuario NO eliminado");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDesR;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtSal;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
